sonar.projectKey=daviddgg271_CSS
sonar.organization=daviddgg271
sonar.projectName=CYCCOMPUTER e-commerce
sonar.sources=client-dashboard/src,backend-apps/src
sonar.sourceEncoding=UTF-8

# TypeScript settings
sonar.typescript.tsconfigPath=client-dashboard/tsconfig.json,backend-apps/tsconfig.json

# Exclusions (tests, dist, node_modules, config files)
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts,**/coverage/**,**/vite.config.ts,client-dashboard/components.json

# Coverage (Backend only, based on Jest config)
sonar.javascript.lcov.reportPaths=backend-apps/coverage/lcov.info
