/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminReportesRouteImport } from './routes/_admin.reportes'
import { Route as AdminProductosRouteImport } from './routes/_admin.productos'
import { Route as AdminPedidosRouteImport } from './routes/_admin.pedidos'
import { Route as AdminNotificacionesRouteImport } from './routes/_admin.notificaciones'
import { Route as AdminInventarioRouteImport } from './routes/_admin.inventario'
import { Route as AdminConfiguracionRouteImport } from './routes/_admin.configuracion'
import { Route as AdminClientesRouteImport } from './routes/_admin.clientes'
import { Route as AdminBuildsRouteImport } from './routes/_admin.builds'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportesRoute = AdminReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificacionesRoute = AdminNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuildsRoute = AdminBuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/builds': typeof AdminBuildsRoute
  '/clientes': typeof AdminClientesRoute
  '/configuracion': typeof AdminConfiguracionRoute
  '/inventario': typeof AdminInventarioRoute
  '/notificaciones': typeof AdminNotificacionesRoute
  '/pedidos': typeof AdminPedidosRoute
  '/productos': typeof AdminProductosRoute
  '/reportes': typeof AdminReportesRoute
}
export interface FileRoutesByTo {
  '/builds': typeof AdminBuildsRoute
  '/clientes': typeof AdminClientesRoute
  '/configuracion': typeof AdminConfiguracionRoute
  '/inventario': typeof AdminInventarioRoute
  '/notificaciones': typeof AdminNotificacionesRoute
  '/pedidos': typeof AdminPedidosRoute
  '/productos': typeof AdminProductosRoute
  '/reportes': typeof AdminReportesRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/builds': typeof AdminBuildsRoute
  '/_admin/clientes': typeof AdminClientesRoute
  '/_admin/configuracion': typeof AdminConfiguracionRoute
  '/_admin/inventario': typeof AdminInventarioRoute
  '/_admin/notificaciones': typeof AdminNotificacionesRoute
  '/_admin/pedidos': typeof AdminPedidosRoute
  '/_admin/productos': typeof AdminProductosRoute
  '/_admin/reportes': typeof AdminReportesRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builds'
    | '/clientes'
    | '/configuracion'
    | '/inventario'
    | '/notificaciones'
    | '/pedidos'
    | '/productos'
    | '/reportes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/builds'
    | '/clientes'
    | '/configuracion'
    | '/inventario'
    | '/notificaciones'
    | '/pedidos'
    | '/productos'
    | '/reportes'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/builds'
    | '/_admin/clientes'
    | '/_admin/configuracion'
    | '/_admin/inventario'
    | '/_admin/notificaciones'
    | '/_admin/pedidos'
    | '/_admin/productos'
    | '/_admin/reportes'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reportes': {
      id: '/_admin/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AdminReportesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/productos': {
      id: '/_admin/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pedidos': {
      id: '/_admin/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notificaciones': {
      id: '/_admin/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AdminNotificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inventario': {
      id: '/_admin/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/configuracion': {
      id: '/_admin/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clientes': {
      id: '/_admin/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/builds': {
      id: '/_admin/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof AdminBuildsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBuildsRoute: typeof AdminBuildsRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminNotificacionesRoute: typeof AdminNotificacionesRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReportesRoute: typeof AdminReportesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBuildsRoute: AdminBuildsRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminNotificacionesRoute: AdminNotificacionesRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReportesRoute: AdminReportesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
